name: Updates publications from Google Scholar
author: safoex
description: comes with automated academicspages template
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: tag
  color: blue